PROMPTS = {}

PROMPTS["entity_extraction"] = """---Goal---
Given a text document, identify all impottant entities from the text.

---Steps---
1. Identify all entities. For each identified entity, extract the following information:
- entity_name: Name of the entity, every word must from the input text, do not change the case of words.

2. Return output in English as a single list of all the entities identified in steps 1.
######################
---Examples---
######################
{examples}

#############################
---Real Data---
######################
Text:
{input_text}
######################
Output:"""

PROMPTS["entity_extraction_examples"] = [
    """Example 1:

Text:
```
Based on the given passages, there are several different phone numbers associated with butcher shops. However, none of them are for a specific location named \"bear\" or have any indication of being related to bears. Therefore, it is unable to determine if there is a butcher shop phone number specifically for \"bear\".
```

Output:
['phone number', 'butcher shop', 'location', 'bears', 'indication']
#############################""",
]

PROMPTS["context_prompt"] = 'Context {num}: "{context}"; Contribution Score {num}: {contribution}\n'
PROMPTS["hallucination_detect_prompt"] = """---Goal---
1. The following is Context information and Contribution Score identified by the attribution algorithm for Current Sentence output by the large language model. 
2. Please determine whether Current Sentence can be derived from Context and whether Current Current Sentence flows smoothly with Previous Sentence.
3. You do not need to consider the semantics of Previous Sentence. 
4. Think step by step, if Current Sentence has no obvious relationship with Context or contains contradictory information with Context, it indicates an hallucination in Current Sentence, and return true. If not, it indicates the Current Sentence is correct, and return false. 
5. For the response, output the following information:
- Lable: one of the following types: ['Evident Baseless Info', 'Evident Conflict', 'Subtle Baseless Info', 'Subtle Conflict', 'None-Hallucination']
- Thought: your reasoning process for determining whether there is hallucination in Current Sentence.
- Hallucination: true if there is hallucination in Current Sentence, otherwise false.
Format the response as JSON {{
  "Lable": "<lable>",
  "Thought": <thought>",
  "Hallucination": <Is_hallucination>
}}
6. The reply format is only JSON. Do not include redundant characters.

---Input Tag Meaning---
Context x: The x-th contextual information.
Contribution Score x: The x-th contextual contribution score for the current sentence.
Previous Sentence: The previous sentence generated by the large language model. 
Current Sentence: The current sentence to be analyzed.

---Real Data---
{context}
Previous Sentence: "{previous}"
Current Sentence: "{current}"
Output:
{{
"""

PROMPTS["hallucination_detect_prompt_noPre"] = """---Goal---
1. The following is Context information and their Contribution Score for Current Sentence output by the large language model. 
2. Please determine whether Context is sufficient for Current Sentence without any other information, and no fictional or contradictory information has been added.
3. If Context is not sufficient for Current Sentence, it indicates an hallucination in Current Sentence, and return true. If Context is sufficient for Current Sentence, it indicates the , return false. 
4. For the response, output the following information:
- Lable: one of the following types: ['Baseless Info', Conflict', 'None-Hallucination']
- Thought: your reasoning process for determining whether there is hallucination in Current Sentence.
- Hallucination: true if there is hallucination in Current Sentence, otherwise false.
Format the response as JSON {{
  "Lable": "<lable>",
  "Thought": <thought>",
  "Hallucination": <Is_hallucination>
}}
5. The reply format is only JSON. Do not include redundant characters.

---Input Tag Meaning---
Context x: The x-th contextual information.
Contribution Score x: The x-th contextual contribution score for the current sentence. Full score is 1.0. 
Current Sentence: The current sentence to be analyzed.

---Real Data---
{context}
Current Sentence: "{current}"
Output:
{{
"""

PROMPTS["hallucination_detect_prompt_llm"] = """
Hallucination refers to the phenomenon where large language models generate content that is inconsistent with the original context.
You are an expert in text hallucination assessment. Generate a JSON evaluation result based on the given context, contribution score, and current sentence. 

Evaluation steps: 
1. Analyze whether the current sentence is based on the provided contextual information 
2. Check for information conflicts or newly introduced information 
3. Classify according to the problem's apparent severity: 
    - "Evident Baseless Info": Clearly introduced information without basis
    - "Evident Conflict": Information clearly conflicting with original text
    - "Subtle Baseless Info": Subtly introduced information without basis
    - "Subtle Conflict": Subtly conflicting with original text
    - "None-Hallucination": No hallucination content 
4. Briefly explain the judgment rationale in "Thought" 
5. Label "true" or "false" in "Hallucination"

Please strictly follow the JSON format below:  
{{
    "Label": "Classification Label", 
    "Thought": "Judgment Reason", 
    "Hallucination": true/false
}}

Now analyze the following content:
{context}
Current Sentence: "{current}"
Output:
{{
"""

PROMPTS["hallucination_detect_prompt_bert_difficult"] = """The following is Context information and their Contribution Score for Current Sentence output by the large language model. Please determine whether Context is sufficient for Current Sentence without any other information, and no fictional or contradictory information has been added. Answer yes or no.
{context}
Current Sentence: "{current}"
Answer: """

PROMPTS["hallucination_detect_prompt_bert"] = """{context}
Current Sentence: "{current}"
"""

example = """
---Examples---
Example 1:
Context 1: "Briefly answer the following question:"; Contribution Score 1: 0.22
Context 2: "Lack of muscle mass:"; Contribution Score 2: 0.14
Context 3: "Based on the provided passages, here is why you may not be getting a toned body despite exercising every day:"; Contribution Score 3: 0.09
Previous Sentence: "Therefore, if you have a high body fat percentage, it could be difficult to achieve a toned appearance, regardless of how much you exercise."
Current Sentence: "Insufficient intensity or duration of workouts: To build muscle and burn fat, your workouts need to be intense enough to challenge your muscles and raise your heart rate."
Output: 
{{
  "Lable": "Evident Baseless Info",
  "Thought": "HIGH INTRO OF NEW INFO\nNo mention of this information.",
  "Hallucination": true
}}

Example 2:
Context 1: "Obtain the Shugabush Monster from the other island."; Contribution Score 1: 0.28
Context 2: "You must obtain the Shugabush Monster from the other island."; Contribution Score 2: 0.18
Context 3: "Briefly answer the following question:"; Contribution Score 3: 0.11
Previous Sentence: "This can be done by visiting the Shugabush Island and collecting the required items to trade with the other island's resident."
Current Sentence: "Hatch the Shugabush Monster to create an egg."
Output: 
{{
  "Lable": "Evident Conflict",
  "Thought": "EVIDENT CONFLICT Original: "...turn your Shugabush Monsters into an egg then you will need to hatch them..." Generative: "Hatch the Shugabush Monster to create an egg."",
  "Hallucination": true
}}

Example 3:
Context 1: "Briefly answer the following question:"; Contribution Score 1: 0.20
Context 2: "It's worth noting that while smoothies can be a helpful tool for weight loss, they should not be relied upon as the sole means of weight management."; Contribution Score 2: 0.18
Context 3: "Some suggestions for making smoothies a weight-loss tool include:"; Contribution Score 3: 0.07
Previous Sentence: "It's worth noting that while smoothies can be a helpful tool for weight loss, they should not be relied upon as the sole means of weight management."
Current Sentence: "A well-balanced diet and regular exercise are still crucial for achieving and maintaining a healthy weight."
Output: 
{{
  "Lable": "Subtle Baseless Info",
  "Thought": "LOW INTRO OF NEW INFO Passages have no mention of this additional tip/information.",
  "Hallucination": true
}}

Example 4:
Context 1: "Briefly answer the following question:"; Contribution Score 1: 0.30
Context 2: "'Based on the provided passages, here are the steps to cook a pork tenderloin roast:'"; Contribution Score 2: 0.12
Context 3: "passage 2:Roast the tenderloin at 450 F for 10 to 15 minutes to aid browning, then reduce the oven to 325 F. Roast the tenderloin until an instant-read thermometer inserted into the thickest part shows an internal temperature of 140 F. Remove the tenderloin from your oven and cover it loosely with aluminum foil.oast the tenderloin at 450 F for 10 to 15 minutes to aid browning, then reduce the oven to 325 F. Roast the tenderloin until an instant-read thermometer inserted into the thickest part shows an internal temperature of 140 F. Remove the tenderloin from your oven and cover it loosely with aluminum foil."; Contribution Score 3: 0.10
Previous Sentence: "Based on the provided passages, here are the steps to cook a pork tenderloin roast:"
Current Sentence: "Preheat the oven to 450°F (232°C) for 10-15 minutes to aid browning, then reduce the oven temperature to 325°F (165°C)."
Output: 
{{
  "Lable": "Subtle Conflict",
  "Thought": "Original: Roast the tenderloin at 450 F for 10 to 15 minutes to aid browning",
  "Hallucination": true
}}

Example 5:
Context 1: "Briefly answer the following question:"; Contribution Score 1: 0.19
Context 2: "Location of involvement: Endometriosis involves the growth of endometrial tissue outside of the uterus, while PCOS is a hormonal disorder that affects the ovaries."; Contribution Score 2: 0.09
Context 3: "Symptoms: Both conditions can cause pain, infertility, and heavy bleeding, but PCOS also presents with acne, weight gain, and excess hair growth."; Contribution Score 3: 0.08
Previous Sentence: "PCOS is characterized by high levels of androgens (male hormones) and low levels of estrogen, while endometriosis does not have a specific hormonal component."
Current Sentence: "In summary, while both conditions can present with similar symptoms, the underlying causes and locations of involvement are different."
Output: 
{{
  "Lable": "None-Hallucination",
  "Thought": "",
  "Hallucination": false
}}"""